// <auto-generated />
namespace sln.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class distance_many_to_many : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(distance_many_to_many));
        
        string IMigrationMetadata.Id
        {
            get { return "201507182258403_distance_many_to_many"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
